version: "3.3"

services:
  postgres:
    image: postgres:14-alpine
    restart: on-failure

    environment:
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "password"
      POSTGRES_DB: "automod"

    ports:
      - "5432:5432"

  redis:
    image: redis:7.0
    restart: on-failure

    ports:
      - "6379:6379"
